version: 0.6
outputdir: ./bin
scripts:
  fmt: goimports -w src
projects:
  - name: dashboard
    type: go
    root: src/bin/dashboard
    imageName: gcr.io/otsimocloud/dashboard
    dockerfile: src/bin/dashboard/Dockerfile
    after: |
      cp "$PROJECT_PATH/sample.yaml" $OUT_PATH
    run: ./dashboard --help
    golang:
      package: bin/dashboard
      cgoEnabled: false
      ldflags: "-w -X main.Version=${BUILD_VERSION}"
      builder: gb
    develop:
      ports:
        - "30860:18860"
  - name: welcome
    type: go
    root: src/bin/welcome
    imageName: otsimo/welcome
    golang:
      package: bin/welcome
      cgoEnabled: false
      ldflags: "-w -X main.Version=${BUILD_VERSION}"
      builder: gb
